<a href="https://colab.research.google.com/github/avinashjairam/avinashjairam.github.io/blob/master/3_6_(basic_numpy_tutorials).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [6]:
#create a numpy array from a list of lists

arr = np.array([[1 , 2, 3], [4, 5, 6], [7, 8, 9]])

#We can access elements of the array by indexing
print(arr[2])

[7 8 9]


In [7]:
#We can create a numpy array of zeros
#Choose your own values for num_rows, num_cols

arr2 = np.zeros([3, 4], dtype = int)

print(arr2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [8]:
#We can create a numpy array of ones
#Choose your own values for num_rows, num_cols

arr3 = np.ones([5, 10], dtype = int)

print(arr3)

[[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [15]:
#We can create a numpy array of random values

#Choose your own values for num_rows, num_cols
#the matrix will have random values between 0 and 10

arr4 = np.random.randint(0,10, size = (5, 5))

print(arr4)


[[2 2 2 2 3]
 [1 3 8 7 3]
 [8 4 7 3 4]
 [3 0 8 8 2]
 [9 0 6 2 9]]
