<a href="https://colab.research.google.com/github/avinashjairam/avinashjairam.github.io/blob/master/basic_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Basic Numpy Operations
import  numpy as np

In [ ]:
#Creating a 3 x 3 numpy array
arr1 = np.array([[2,3,5],[5,0,8], [8,9,3]])

print(arr1)

[[2 3 5]
 [5 0 8]
 [8 9 3]]


In [ ]:
#Creating a 3 x 3 numpy array
arr2 = np.array([[1 , 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#Creating a 5 x 5 array of zeros
arr3 = np.zeros([5, 5], dtype = int)
print(arr3)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [ ]:
#Creating a 5 x 5 array of zeros
arr4 = np.ones([5, 5], dtype = int)

print(arr4)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
#Creating a 10 x 10 array of random numbers in the range 0 - 10 not inclusive
arr5 = np.random.randint(0,10, size = (10, 10))
print(arr5)


[[3 3 9 0 6 3 4 1 7 7]
 [3 8 4 8 2 0 7 3 3 1]
 [0 3 2 8 2 5 9 8 5 1]
 [0 7 0 3 4 7 6 6 4 6]
 [9 0 7 0 0 1 9 7 4 4]
 [0 6 7 5 3 7 3 1 8 7]
 [9 5 9 0 4 0 3 2 7 3]
 [5 2 1 6 3 9 3 2 1 5]
 [1 8 1 4 2 0 3 3 7 6]
 [6 0 4 2 8 0 4 4 2 5]]


In [ ]:
#Creating a 2 x 2 array of random numbers in the range 0 - 5 not inclusive
arr6 = np.random.randint(0,5, size = (2, 2))
print(arr6)

[[2 2]
 [4 1]]


In [ ]:
#Finding the sum of values in arr6
np.sum(arr6)

9

In [ ]:
#Multiplying two arrays
np.multiply(arr5, arr5)

array([[ 9,  9, 81,  0, 36,  9, 16,  1, 49, 49],
       [ 9, 64, 16, 64,  4,  0, 49,  9,  9,  1],
       [ 0,  9,  4, 64,  4, 25, 81, 64, 25,  1],
       [ 0, 49,  0,  9, 16, 49, 36, 36, 16, 36],
       [81,  0, 49,  0,  0,  1, 81, 49, 16, 16],
       [ 0, 36, 49, 25,  9, 49,  9,  1, 64, 49],
       [81, 25, 81,  0, 16,  0,  9,  4, 49,  9],
       [25,  4,  1, 36,  9, 81,  9,  4,  1, 25],
       [ 1, 64,  1, 16,  4,  0,  9,  9, 49, 36],
       [36,  0, 16,  4, 64,  0, 16, 16,  4, 25]])